# this is an example compose file
services:
  spam-filter:
    image: docker.io/webscrubbing808/simple-activitypub-spam-filter:v0.1.0
    ports:
      - "8080:8080"
    environment:
      - BLOCK_WORDS="THE_EXAMPLE_SPAM_URL.org,EXAMPLE_WORDS"
      - LISTEN_ADDRESS="0.0.0.0:8080"
      - WHEN_DETECT_SPAM="block"
      - PROXY_TARGET="http://example_my_mastodon_server"
